/**:
  lidar_front:
    sllidar_node:
      ros__parameters:
        channel_type: serial
        serial_port: /dev/rplidar_front
        serial_baudrate: 1000000
        frame_id: lidar_front
        angle_compensate: true
        scan_mode: DenseBoost

  lidar_rear:
    sllidar_node:
      ros__parameters:
        channel_type: serial
        serial_port: /dev/rplidar_rear
        serial_baudrate: 1000000
        frame_id: lidar_rear
        angle_compensate: true
        scan_mode: DenseBoost

  camera_front:
    ros__parameters:
