/**/controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

/**/joint_state_broadcaster:
  ros__parameters:
    # publish default joint states for passive joints
    extra_joints:
      - castor_wheel_fl_link_joint
      - castor_wheel_fr_link_joint
      - castor_wheel_rl_link_joint
      - castor_wheel_rr_link_joint
      - castor_wheel_fl_joint
      - castor_wheel_fr_joint
      - castor_wheel_rl_joint
      - castor_wheel_rr_joint

/**/diff_drive_base_controller:
  ros__parameters:
    left_wheel_names: [wheel_left_joint]
    right_wheel_names: [wheel_right_joint]

    wheel_separation: 0.36
    wheel_radius: 0.06

    publish_rate: 100.0
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_footprint
