/**/controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

/**/joint_state_broadcaster:
  ros__parameters:
    # publish default joint states for passive joints
    extra_joints:
      - fl_castor_wheel
      - fr_castor_wheel
      - rr_castor_wheel
      - rl_castor_wheel
      - fl_wheel
      - fr_wheel
      - rr_wheel
      - rl_wheel

/**/diff_drive_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel"]
    right_wheel_names: ["right_wheel"]

    wheel_separation: 0.36
    wheel_radius: 0.06

    publish_rate: 100.0
    enable_odom_tf: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"
